---
title: "OPTICS_kxi Extraction_env"
author: Hannah Safford
date: "February 2, 2022"
output: html_notebook
---

```{r}
## LOAD LIBRARIES
library(opticskxi)
library(ggplot2)
library("RColorBrewer")
library("tidyverse")
require(gtools)
```

```{r}
## DEFINE GLOBAL VARIABLES
dataFileDirectory = "scaledData/" # Directory of .csv files containing the transformed FCM data as well as corresponding .rda files containing the OPTICS objects (organized into folders with dilutionFolders names)
saveFileDirectory = "clusteredData/"
dilutionFolders = c("filteredEff10xPos","filteredEff10xNeg")
replicates = c("Rep 1","Rep 2","Rep 3","Rep 4","Rep 5","Rep 6","Rep 7","Rep 8","Rep 9","Rep 10")
```

```{r}
## READ IN TRANSFORMED FCM DATA AND LOAD OPTICS OBJS TO WORKSPACE
fileNames = list()
repData = list()
repOrdered = list()
data = list()
ordered = list()

x = length(dilutionFolders)
y = length(replicates)

for (i in 1:x) {
  temp = mixedsort(list.files(paste(dataFileDirectory,dilutionFolders[i],"/",sep=""),pattern="*.csv"))
  temp=lapply(temp,function(x) paste(dataFileDirectory,dilutionFolders[i],"/",x,sep=""))
  fileNames[i]=list(temp)
  
  for (j in 1:y) {
    opticsFile = gsub("csv","rda",fileNames[[i]][[j]])
    # opticsFile = gsub("Rep","noFSC_Rep",opticsFile) # Uncomment if not considering FSC dimension
    load(file = opticsFile)
    repData[j] = list(read.csv(fileNames[[i]][[j]]))
    repOrdered[j] = list(temp_obj) # temp_obj name comes from .rda file generated by OPTICS_Ordering script
  }
  
  data[i] = list(repData)
  ordered[i] = list(repOrdered)
}
```

```{r}
## EXTRACT CLUSTERS USING KXI METHOD
MAXLOOP = 1000 # Maximum # of times to iterate through kxi algorithm
N_XI = 4 # Maximum number of clusters for the algorithm to identify
points = c(8000,8000) # Minimum number of points in each cluster

yReachMax = 0.1 # Set to epsilon used for OPTICS ordering
xScatterLim = c(10,197360) # Limits selected to match FlowJo output
yScatterLim = c(800,474341.6491) # Limits selected to match FlowJo output

# Set plot color scheme
light_col<-brewer.pal(n=N_XI,name='Set1')
light_col[4] = "#E6AB02"
light_col[6] = "#F0027F"

cluster = list()
clusters = list()

for (i in 1:x) {
  if (i == 1) {
    dilution = "Positive"
  }
  if (i == 2) {
    dilution = "Negative"
  }
  PTS = points[i]
  
  for (j in 1:y) {
    opticsData = data[[i]][[j]]
    opticsObj = ordered[[i]][[j]]
    
    opticsObj$reachdist[!is.finite(opticsObj$reachdist)] = 0 # Set infinite reachability distances to zero (for better visualization on plot)
    opticsObj$predecessor[!is.finite(opticsObj$predecessor)] <- 0
    
    cluster[j] = list(opticskxi(opticsObj, n_xi = N_XI, pts = PTS, max_loop = MAXLOOP)) # This is the kxi clustering
    
    # Assign kxi cluster output to the table for later storage
    opticsData$Clusters <- as.factor(cluster[[j]])
    opticsData$Order = opticsObj$order
    opticsData$Reach = opticsObj$reachdist
    opticsData$Pred = opticsObj$predecessor

    # Do some reordering of the data for manual extraction
    Index = c(1:length(opticsData$Order))
    b = data.frame(Index,Order=opticsData$Order)
    b = b[order(b$Order),]
    b$Reach = opticsData$Reach
    b = b[order(b$Index),]
    opticsData$Index = b$Index
    opticsData$Reach = b$Reach
    
    replicate = as.character(j)
    title = paste(dilution,", With FSC, Replicate ",replicate,sep="")
    # title = paste(dilution,", No FSC, Replicate ",replicate,sep="") Uncomment if not considering FSC

    # Reachability plot
    p<-ggplot_optics(opticsObj,groups = cluster[[j]],colors=light_col)
    p<-p + ylim(0,yReachMax)+ylab("Reachability distance")+ggtitle(title)+ theme(plot.title = element_text(hjust = 0.5))

    # Scatter plot
    p2<-ggplot(opticsData, aes(x=SSC,y=FITC,color=Clusters))+geom_point(shape = 16, size = 0.5)+scale_color_manual(values=light_col)
    p2<-p2 + scale_x_continuous(trans = 'log10',limits = xScatterLim,expand = c(0,0)) +
  scale_y_continuous(trans = 'log10',limits = yScatterLim,expand = c(0,0)) + guides(color = guide_legend(override.aes = list(size=2))) + theme_bw() + ggtitle(title) + theme(plot.title = element_text(hjust = 0.5))

    # Save data and plots
        saveData = paste(saveFileDirectory,"kxiClustering/data/",dilutionFolders[i],"/_Rep",replicate,"_data.csv",sep="") # Filename for saving the data (now labeled with kxi cluster number, order, reachability, predecessor) in a new directory
    saveReach = paste(saveFileDirectory,"kxiClustering/plots/",dilutionFolders[i],"/_Rep",replicate,"_reach.png",sep="") # Filename for saving the reachability plot
    saveScatter = paste(saveFileDirectory,"kxiClustering/plots/",dilutionFolders[i],"/_Rep",replicate,"_scatter.png",sep="") # Filename for saving the colored scatter plot
    
    write.csv(opticsData,saveData)
    ggsave(p, filename = saveReach, width = 8, height = 6, units = "in")
    ggsave(p2, filename = saveScatter, width = 8, height = 6, units = "in")
  }
  
  clusters[i] = list(cluster)
}
```

```{r}
## COUNT KXI CLUSTERS
dataFileNames = list()
repData = list()
data = list()

x = length(dilutionFolders)
y = length(replicates)

for (i in 1:x) {
  dilution = as.character(2^(i-1))
  temp = mixedsort(list.files(paste(saveFileDirectory,"kxiClustering/data/",dilution,"x/",sep=""),pattern="*.csv"))
  temp=lapply(temp,function(x) paste(saveFileDirectory,"kxiClustering/data/",dilution,"x/",x,sep=""))
  dataFileNames[i] = list(temp)

  for (j in 1:y) {
    repData[j] = list(read.csv(dataFileNames[[i]][[j]]))
  }
  
  data[i] = list(repData)
  ordered[i] = list(repOrdered)
}

freq = list()
freqs = list()

for (i in 1:x)
{
  for (j in 1:y)
  {
    tempObj = data[[i]][[j]]
    c = table(tempObj$Clusters)
    d = length(tempObj$Index) - sum(c)
    c = as.data.frame(c)
    c[7,2] = d
    freq[j] = list(c$Freq)
  }
freqs[i] = list(freq[j])
}
```