---
title: "OPTICS_Manual Extraction_env"
author: Hannah Safford
date: "February 2, 2022"
output: html_notebook
---

```{r}
## LOAD LIBRARIES
library(opticskxi)
library(ggplot2)
library("RColorBrewer")
library("tidyverse")
require(gtools)
```

```{r}
## DEFINE GLOBAL VARIABLES
manualGroupFile = "manualGroupsEnv.csv" # .csv file containing start and end points of manually identified valleys
dataFileDirectory = "clusteredData/kxiClustering/data/" # Directory of .csv files containing the transformed FCM data labeled with kxi clusters (organized into folders with dilutionFolders names)
opticsFileDirectory = "scaledData/" # Directory of .rda files containing the OPTICS objects (organized into folders with dilutionFolders names)
saveFileDirectory = "clusteredData/"
dilutionFolders = c("filteredEff10xPos","filteredEff10xNeg")
replicates = c("Rep 1","Rep 2","Rep 3","Rep 4","Rep 5","Rep 6","Rep 7","Rep 8","Rep 9","Rep 10")
```

```{r}
## READ IN TRANSFORMED FCM DATA AND LOAD OPTICS OBJS TO WORKSPACE
dataFileNames = list()
opticsFileNames = list()
repData = list()
repOrdered = list()
data = list()
ordered = list()

x = length(dilutionFolders)
y = length(replicates)

for (i in 1:x) {
  temp = mixedsort(list.files(paste(dataFileDirectory,dilutionFolders[i],"/",sep=""),pattern="*.csv"))
  temp=lapply(temp,function(x) paste(dataFileDirectory,dilutionFolders[i],"/",x,sep=""))
  dataFileNames[i]=list(temp)
  
  temp = mixedsort(list.files(paste(opticsFileDirectory,dilutionFolders[i],"/",sep=""),pattern="*.rda"))
  temp=lapply(temp,function(x) paste(opticsFileDirectory,dilutionFolders[i],"/",x,sep=""))
  opticsFileNames[i]=list(temp)
  
  for (j in 1:y) {
    load(file = opticsFileNames[[i]][[j]]) # Change to j + 10 if considering with FSC
    repData[j] = list(read.csv(dataFileNames[[i]][[j]]))
    repOrdered[j] = list(temp_obj) # temp_obj name comes from .rda file generated by OPTICS_Ordering script
  }
  
  data[i] = list(repData)
  ordered[i] = list(repOrdered)
}
```

```{r}
## READ IN MANUAL GROUP FILE
manualGroups = read.csv(manualGroupFile)
```

```{r}
## ASSIGN AND PLOT MANUAL CLUSTERS
clusterList = list()

yReachMax = 0.1 # Set to epsilon used for OPTICS ordering
xScatterLim = c(10,197360) # Limits selected to match FlowJo output
yScatterLim = c(800,474341.6491) # Limits selected to match FlowJo output

# Set plot color scheme
light_col<-brewer.pal(n=7,name='Set1')
light_col[4] = "#E6AB02"
light_col[6] = "#F0027F"

for (i in 1:x) {
    if (i == 1) {
    dilution = "Positive"
  }
  if (i == 2) {
    dilution = "Negative"
  }
  
  for (j in 1:y) {
    index = 10*(i-1)+j
    opticsData = data[[i]][[j]]
    object = ordered[[i]][[j]]
    reachDist = object$reachdist[object$order]
    
    groups = manualGroups[[index]][!is.na(manualGroups[[index]])]
    z = length(groups)
    
    a = length(opticsData$FSC)
    b = rep(NA, a)
    cluster = 1
    
    for (k in 1:z) {
      
      if (k==1) {
        start = 1
      }
      
      else {
        start = groups[[k-1]]
      }
      
      if (k==z) {
        end = groups[[k]]
        # end = a
      }
      else {
        end = groups[[k]]
      }
      
      if (k%%2!=0) {
        b[start:end]=cluster
        cluster = cluster + 1
      }
    }
    
    clusterList[index] = list(b)
    clusters = b
    clusters[object$order] <- clusters
    object$clusters <- clusters
    opticsData$ManualExt = clusters
    
    replicate = as.character(j)
    title = paste(dilution,", No FSC",sep="")
    
    opticsData$ManualExt = as.factor(opticsData$ManualExt)
    opticsData = opticsData[order(opticsData$ManualExt,na.last = FALSE),]
        
    p<-ggplot_optics(object,groups = clusters,colors=light_col)
        p<-p + ylim(0,yReachMax)+ylab("Reachability distance")+ggtitle(title)+ theme(plot.title = element_text(hjust = 0.5))
        
    p2<-ggplot(opticsData, aes(x=SSC,y=FITC,color=ManualExt))+geom_point(shape = 16, size = 0.5, alpha = 0.5)+scale_color_manual(values=light_col)
    p2<-p2 + scale_x_continuous(trans = 'log10',limits = xScatterLim,expand = c(0,0)) +
    scale_y_continuous(trans = 'log10',limits = yScatterLim,expand = c(0,0)) + guides(color = guide_legend(override.aes = list(size=2))) + theme_bw() + ggtitle(title) + theme(plot.title = element_text(hjust = 0.5)) + labs(color = "Clusters")
    
            saveData = paste(saveFileDirectory,"manualClustering/data/",dilutionFolders[i],"/Rep",replicate,"_data.csv",sep="") # Filename for saving the data (now labeled with manual cluster number) in a new directory
    saveReach = paste(saveFileDirectory,"manualClustering/plots/",dilutionFolders[i],"/Rep",replicate,"_reach.png",sep="") # Filename for saving the reachability plot
    saveScatter = paste(saveFileDirectory,"manualClustering/plots/",dilutionFolders[i],"/Rep",replicate,"_scatter.png",sep="") # Filename for saving the colored scatter plot
    
    # Uncomment to save annotated data and plots
    write.csv(opticsData,saveData)
    ggsave(p, filename = saveReach, width = 8, height = 6, units = "in")
    ggsave(p2, filename = saveScatter, width = 8, height = 6, units = "in")
  }
}
```

```{r}
## COUNT MANUAL CLUSTERS
dataFileNames = list()
repData = list()
data = list()

x = length(dilutionFolders)
y = length(replicates)

for (i in 1:x) {
  dilution = as.character(2^(i-1))
  temp = mixedsort(list.files(paste(saveFileDirectory,"manualClustering/data/",dilution,"x/",sep=""),pattern="*.csv"))
  temp=lapply(temp,function(x) paste(saveFileDirectory,"manualClustering/data/",dilution,"x/",x,sep=""))
  dataFileNames[i] = list(temp)

  for (j in 1:y) {
    repData[j] = list(read.csv(dataFileNames[[i]][[j]]))
  }
  
  data[i] = list(repData)
  ordered[i] = list(repOrdered)
}

freq = list()
freqs = list()

for (i in 1:x)
{
  for (j in 1:y)
  {
    tempObj = data[[i]][[j]]
    c = table(tempObj$ManualExt)
    d = length(tempObj$Index) - sum(c)
    c = as.data.frame(c)
    c[7,2] = d
    freq[j] = list(c$Freq)
  }
freqs[i] = list(freq[j])
}
```